# Generated by Django 5.2.7 on 2025-10-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('contenue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('prenom', models.CharField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cours')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='Professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professeur'),
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField()),
                ('date', models.DateField()),
                ('lien_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cours')),
            ],
        ),
    ]
