# Generated by Django 5.2.7 on 2025-11-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='fichier',
            field=models.FileField(null=True, upload_to='public'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='contenue',
            field=models.FileField(null=True, upload_to='public'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
